

DROP FUNCTION IF EXISTS "InsertUser";
DROP FUNCTION IF EXISTS "InsertCourse";
DROP FUNCTION IF EXISTS "InsertCourseMember";
DROP FUNCTION IF EXISTS "InsertAssignment";
DROP FUNCTION IF EXISTS "InsertAssignmentAttachment";

DROP FUNCTION IF EXISTS "GetUserByIdentifier";
DROP FUNCTION IF EXISTS "GetUserById";

DROP FUNCTION IF EXISTS "GetCourseByCode";
DROP FUNCTION IF EXISTS "GetCoursesByUserId";

DROP FUNCTION IF EXISTS "GetCourseMembersByCourseId";

